name: "Frogbot Scan Pull Request"
on:
  push:
    branches: 
      - "main"
      - "homework/ci-pipeline"
      - "features/jfrog-ci-pipeline"
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "deliverables/**"
  workflow_dispatch:
  
permissions:
  pull-requests: write
  contents: read
  id-token: write
jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    # A pull request needs to be approved, before Frogbot scans it. Any GitHub user who is associated with the
    # "frogbot" GitHub environment can approve the pull request to be scanned.
    # Read more here (Install Frogbot Using GitHub Actions): https://github.com/jfrog/frogbot/blob/master/docs/install-github.md
    environment: frogbot
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      #  IMPORTANT:
      #  1. See the following link for information about the tools that need to be installed for Frogbot to work - https://github.com/jfrog/frogbot/tree/master/docs/templates/github-actions/scan-and-fix
      #  2. Some projects require creating a frogbot-config.yml file. Read more about it here - https://github.com/jfrog/frogbot/blob/master/docs/frogbot-config.md

      - uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: oidc-test-mikios/spring-petclinic@github
        env:
          JFROG_CLI_LOG_LEVEL: DEBUG
          # JFrog platform URL
          JF_URL: https://${{ vars.JF_REGISTRY }}/
          JF_PROJECT: alexwang
          JF_GIT_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
